### ISSUE TITLE
Log output: Double constant parameter display values are sometimes truncated

### ISSUE THREAD

**Issue by kleinj** [prismmodelchecker/prism#1]
In the log output, the values of double constants (either directly set from the command line or via experiments) are only displayed with a maximum of 6 fraction digits. In some cases, this can lead to suboptimal output:

    $ prism -const k=1E-7 ....
    [....]
    Building model...
    Model constants: k=0

The output is formatted via `parser.Values.toString()`, which uses `parser.Values.valToString()`. This converts double values with only 6 fraction digits.

It might be an option to use `PrismUtils.formatDouble()` instead.

**Comment by davexparker** [comment]
Yes, not ideal. Should fix.

**Comment by kleinj** [comment]
PrismUtils.formatDouble uses the `%g` format string, i.e., the shorter of scientific or decimal notations. So, the result would be 

```
Building model...
Model constants: k=1e-07
```

for both `-const k=1E-07` and `-const k=0.0000001`. Are we ok with that?

**Comment by davexparker** [comment]
I think this is fine. It's consistent and predictable. And usually more readable.

**Comment by kleinj** [comment]
Fixed in SVN 11760.
