### ISSUE TITLE
Allow multiple properties to be selected with -property switch.

### ISSUE THREAD

**Issue by kleinj** [prismmodelchecker/prism#107]
On the mailing list, there was the suggestion to extend the `-property` switch to allow more complex selections, e.g.:

```
-property 1,3,4
-property a,b,c
-property a,3,d
```

Looking at the code, would be a relatively easy addition (and backward compatible).
https://github.com/prismmodelchecker/prism/blob/7b8a4628d06666dcf4f2da3982cfb201fe32b36f/prism/src/prism/PrismCL.java#L674

**Comment by merkste** [comment]
This would be really useful. I've prepared a little something.
