### ISSUE TITLE
Tiebraking of the new round operator

### ISSUE THREAD

**Issue by tquatmann** [prismmodelchecker/prism#118]
The [documentation](http://www.prismmodelchecker.org/manual/ThePRISMLanguage/Expressions) is not very explicit about rounding of halfway cases.

I think the rounding is always towards infinity, as the following model yields just one state:
```
dtmc

module main
x : [1..2] init 1;
[] x = -round(-0.5) -> (x'=2);
endmodule
```
Can you confirm this?

Notice that rounding of halfway cases in C/C++ is by default 'away from zero', while java.lang.Math.round() rounds towards infinity.

**Comment by merkste** [comment]
Yes, rounding towards infinity is the expected behavior. We should clarify this in the documentation. Round is implemented either via `java.lang.Math#round` or via some variant of `round(x) = floor(x + 1/2)`

**Comment by tquatmann** [comment]
Thank you for the clarification :)

**Comment by davexparker** [comment]
Thanks @tquatmann. Now documented at http://www.prismmodelchecker.org/manual/ThePRISMLanguage/Expressions.
