### ISSUE TITLE
Regression: computation of S-operator probabilities does not converge (sparse, hybrid, mtbdd)

### ISSUE THREAD

**Issue by merkste** [prismmodelchecker/prism#119]
In previous versions of Prism (*), the computation of `S=? [ all_damaged ]` (`K=2, WRITER_START=1`) converges for the attached model. However, in the current release it converges only using the explicit engine.

* [writers-3.txt](https://github.com/prismmodelchecker/prism/files/3167002/writers-3.txt)
* (*) Around commit 86438e9

Edit: Fixed commit and typo in property.

**Comment by kleinj** [comment]
Hi,
could you clarify a few bits?
* The commit you listed is not in the PRISM repo, but I found it in one of the repos where we did the svn->git conversion ourselves. The corresponding commit seems to be 86438e9d789b31d23ae3e6a7004db8c15063ba0b, is that right?
* As the property, you presumably mean `S=?[ all_damaged ]` instead?
* I've built the commit above and, with that property, the computation does not converge. I.e. I can't reproduce the convergence you have observed. I went back to the start of 2015, same result.

The model converges very fast with `-power`. We should really think about making that (or `-gs`) the default for the symbolic engines for steady-state computations (see also the last comment in #49).

**Comment by merkste** [comment]
@kleinj I am sorry for the confusion. I accidentally had the power-method in PrismSettings for the old version. Yes, it does not converge with the default setting.

> The model converges very fast with -power. We should really think about making that (or -gs) the default for the symbolic engines for steady-state computations (see also the last comment in #49).

I have a dedicated setting for the approximation method for steady-state probabilities in my L-operator branch which defaults to power. How about contributing this as a separate PR?

**Comment by kleinj** [comment]
> How about contributing this as a separate PR?

No worries. Sure, why not, let's have a look.
