### ISSUE TITLE
Support for HiDPI?

### ISSUE THREAD

**Issue by mikucionisaau** [prismmodelchecker/prism#12]
We are trying to use PRISM on Windows laptops with HiDPI screens (with dpi settings greater or equal to 192dpi, resolution 3200x1800 and higher), but the text and widgets are unreadably small with JVM 8.

I believe this issue is systemic between JVM and Windows OS, so I tried Java 9 which implements JEP 263 (HiDPI support for Windows), but then PRISM does not start: it shows splash screen and exits shortly. It does not show any diagnostic information on the command line either.

Do you have any treatment to address HiDPI screens?
Is there a way to turn on more diagnostics? (I have modified xprism.bat to stay with current command line window, but it does not show anything)

**Comment by kleinj** [comment]
Hi,

thanks for your bug report. I've split the crash issue into a seperate bug (see #13). Generally, if PRISM crashes hard (such as here with some segmentation fault in the native code), the Java runtime generates hs_err_pidXXX.log logfiles with details about the crash.

As it seems that the 32bit version of PRISM works with JVM9 on Windows, it would be great if you could give that a try to see if switching to JVM9 solves the DPI issue. Note that you need a 32bit version of JVM9 as well...

Otherwise, I can try to reproduce in a virtual machine.

**Comment by kleinj** [comment]
Ok, I ran the PRISM 4.3.1 GUI (32bit) on a VM with Window 10, JRE9 (32bit) and a resolution of 3268x1970. The GUI reacted to changes in the DPI setting of Windows (Display, "Change the size of text and other items: x%") on the fly. Using something like 175% or 200%, the GUI is quite usable, with reasonable font sizes.

Some observations:
 - The font size in the title bar is quite small, as well for the dialog title bars.
 - When changing the DPI setting while the PRISM GUI is running, the experiment plots look quite pixelish. Starting up with the same setting it looks ok.

So, at the moment it looks like if you use HiDPI screens on Windows, you are limited to the 32bit version of PRISM, but that is usable with JDK9... When #13 is fixed, 64bit should also work.


Some screenshots of the editor and the experiments plot view for 100%, 200% and 300%:

100%:

![editor-100](https://cloud.githubusercontent.com/assets/7789974/20008593/7cebcc58-a2a1-11e6-8eee-7cfd90dc034e.png)
![experiments-100](https://cloud.githubusercontent.com/assets/7789974/20008642/a8179c22-a2a1-11e6-8759-0a2a82212d07.png)

200%:
![editor-200](https://cloud.githubusercontent.com/assets/7789974/20008658/b93b7096-a2a1-11e6-8184-7b3eaac43a66.png)
![experiments-200](https://cloud.githubusercontent.com/assets/7789974/20008669/c2b77f98-a2a1-11e6-80de-bcebc946f99e.png)

300%:
![editor-300](https://cloud.githubusercontent.com/assets/7789974/20008689/d29e0b0c-a2a1-11e6-9267-410625eae968.png)
![experiments-300](https://cloud.githubusercontent.com/assets/7789974/20008694/d7354a72-a2a1-11e6-95bd-90e5693a197b.png)

**Comment by mikucionisaau** [comment]
I just installed 32bit Java9 and 32bit Prism and it looks good: menus and widgets are readable and accessible. 
Thank you!
