### ISSUE TITLE
Should Model Label Sets be Ordered?

### ISSUE THREAD

**Issue by lisaoakley** [prismmodelchecker/prism#143]
Hello!

I am modifying the `explicit.ModelModelGenerator` class to implement the methods `isLabelTrue` using the `explicit.Model` interface.

I have no trouble with `isLabelTrue(String label)`, but `isLabelTrue(int i)` is giving me pause. 

The description of this method is: `Is the ith label of the model true in the state currently being explored`. However, the `getLabels` method of `explicit.Model` method returns a `Set<String>`. Since Sets are unordered, I do not understand what the `ith` label of the model would mean.

There are two possible directions:
1. There is an ordering of the labels in a model, in which case, the `getLabels` method of `explicit.Model` would return a `List<String>` rather than a Set.
2. There is no ordering of the labels in a model, in which case, the `isLabelTrue(int i)` method of `explicit.ModelGenerator` should be eliminated from the interface, leaving only `isLabelTrue(String label)`.

Direction 2 (no ordering of labels) makes more sense to me personally. I don't know what kind of ripple effect these changes would make to the rest of the project, if any. On a quick search over the code, I see that `explicit.ConstructModel` and `explicit.ModelGenerator2MTBDD.java` both use `isLabelTrue(int i)` to iterate through the labels. 

It seems that Direction 1 might be the easier fix, and labels could just have arbitrary ordering (which seems to be the case in the above usage of `isLabelTrue(int i)` anyways.

Does anyone have thoughts on how this should be approached?

**Comment by davexparker** [comment]
Hi @lisaoakley. Good question. Even though a PRISM user would only ever refer to a label by name, there _is_ a natural order to them (the order that they appear in the model file) and they might expect this order to be preserved, e.g., when exporting model information to files. Also, from an efficiency perspective, it would be less efficient to query labels by name in every state during model construction. So I think it is preferable to assume that labels are ordered.

In the `Model` classes, the usage is a bit different: labels are not queried per individual state, and extra labels are sometimes added dynamically during model checking. Which explains the current usage of sets/maps. However I don't think it would be too disruptive to enforce an additional order upon the labels, and therefore make `Model.getLabels()` return a `List` not a `Set`. When you convert a `Model` to a `ModelGenerator`, would you actually need the ordering of labels to be preserved? If not, the easiest solution would be to just fix an arbitrary ordering when implementing the conversion?

**Comment by lisaoakley** [comment]
@davexparker, thank you for your speedy responses!

I personally do not need the ordering of the labels preserved, however arbitrarily ordering an unordered set could be misleading to a user of the `explicit.ModelModelGenerator` class. 

Another option is to throw a  `PrismNotSupportedException` which reads `Labels in the explicit.Model interface are unordered`. Does that sound like a reasonable solution?

**Comment by davexparker** [comment]
Wouldn't a better solution be to fix an ordering and document it in the javadoc (alphabetical by name would be the most obvious), so there is some way to preserve labels if required?

**Comment by lisaoakley** [comment]
Yes! That will work, thanks.
