### ISSUE TITLE
Will synthesis of DTMC for given (PO)MDP be included in official PRISM?

### ISSUE THREAD

**Issue by proteusGIT** [prismmodelchecker/prism#146]
Hi,

I have playing around with the POMDP synthesis implementation [RTS-POPTAS](http://www.prismmodelchecker.org/files/rts-poptas/ ).
I also had a look at [NFM18](http://www.prismmodelchecker.org/files/nfm18/).

Will these be included in PRISM eventually?
I believe to have resolved my previous issue with that contribution in the meantime.

Best.

**Comment by gethin-norman** [comment]
These are generated by exporting the strategy (or adversary) which is essentially the DTMC (although it includes the choices in all the states of the MDP) see:

http://www.prismmodelchecker.org/manual/RunningPRISM/Adversaries

In the case of POMDPs this is a little bit difficult to understand as it is a strategy of the belief MDP. The format of each line of the output is:

state number:(values of visible variables),[belief probabilities for values of hidden variables] & no-det number/probability @ (new values of visible variables) > new state number:(new values of visible variables),[new belief probabilities for values of hidden variables]

However, a student developed a prototype tool which generates a graphical representation of the strategy (it generates a dot file). It is available on github:

https://github.com/munroa/PRISM-POMDP-Analyser

thanks

Gethin

**Comment by davexparker** [comment]
Hi @proteusGIT. As Gethin says, you can use `-exportadv` to get a view of the model used to synthesise a POMDP strategy. If you are interested, there is a newer version of the code, hopefully to be integrated into the main PRISM release quite soon:

https://github.com/davexparker/prism/tree/pomdps

If you use `-exportadv` on that version, you get a standard PRISM `.tra` file representing the model, and also a `dot` file which annotates with info about the belief states. Here's part of an example:

![image](https://user-images.githubusercontent.com/6075003/103637429-63298280-4f43-11eb-94af-c8d2c09a2789.png)

**Comment by davexparker** [comment]
Hi @proteusGIT. DTMC policy export for POMDPs is now in the [main codebase](https://github.com/prismmodelchecker/prism) and also the [public release](http://www.prismmodelchecker.org/download.php). Use:

`prism pomdp.prism pomdp.props -exportadv adv.dot`
