### ISSUE TITLE
Build For Mac xARM64

### ISSUE THREAD

**Issue by JustinKottinger** [prismmodelchecker/prism#150]
Hi everyone, 

I am wondering if it is possible to install and use the Prism Model Checker on the new M1 Macs running the xARM64 architecture? I saw a Pull Request #140 suggesting that this sort of thing should be possible but I am still having issues. I ran the following script:

`make ARCH=aarch64`

I have also copied the terminal output for anyone's review. 

[prismMakeOutput.txt](https://github.com/prismmodelchecker/prism/files/5953765/prismMakeOutput.txt)

I should also note that just running `make` with "OSTYPE/ARCH: darwin x86_64" is able to build but running `bin/xprism` (obviously) fails due to the program being built in the incorrect architecture. 

Any help on this would be greatly appreciated. Thank you in advance for your time.

**Comment by davexparker** [comment]
Hi @JustinKottinger. It would be great to get PRISM building on Arm-based Macs, although unfortunately I do not have a machine available to test it out. The PR you mentioned is actually for Linux. The Mac-specific build instructions currently ignore any `ARCH` other than `x86_64`.

I created a branch and added a first attempt at compiling for `arm64`. If you're willing to try it out, you can do:

```
git clone https://github.com/davexparker/prism -b arm64 prism-arm64
cd prism-arm64/prism
make
make test
```

I am quite unlikely to get it right first time though...

**Comment by davexparker** [comment]
Hi @JustinKottinger. Did you get a chance to look at this? It would be good to enable this in the next release if it works.

**Comment by JustinKottinger** [comment]
Hi @davexparker. I did look at this. Unfortunately, the `make` command failed. I have saved the terminal output for your records. Not entirely sure how you plan to proceed, but I would be willing to help test future versions of this branch if needed. Thanks in advance!
[prismArm_TerminalOutput.txt](https://github.com/prismmodelchecker/prism/files/6004006/prismArm_TerminalOutput.txt)

**Comment by davexparker** [comment]
Thanks! Looks like a silly typo on my part (probably not the last). If you `git pull` from that same repo and then rebuild (`make clean_all && make && make test`), we can try again.

**Comment by JustinKottinger** [comment]
Just tried again. Different error this time. Attaching the terminal output.
[prismArmTerminalOutput2.txt](https://github.com/prismmodelchecker/prism/files/6012071/prismArmTerminalOutput2.txt)

**Comment by davexparker** [comment]
Thanks again. That's an error in building the underlying CUDD library. It uses a function that gives a deprecation warning for me, but I guess it has been removed in this newer version of the OS. I pushed another fix to the same branch.

**Comment by JustinKottinger** [comment]
This most recent attempt worked for me. I think it is ready to be included into the next release. Thank you so very much.

**Comment by davexparker** [comment]
Excellent! Thank you too. I'll the test CUDD change on a few more OSs and then merge the fix into the main codebase.
