### ISSUE TITLE
Mac M1

### ISSUE THREAD

**Issue by cap508** [prismmodelchecker/prism#161]
Hi I am trying to install Prism on a new Mac with an M1 processor. I have upgraded Java to v11 and now I am getting a 'wrong architecture error'. Any thoughts/workarounds?

Although the screenshot is prism 4.6 I get the same error for 4.7.

<img width="772" alt="Screenshot 2021-06-08 at 10 28 59" src="https://user-images.githubusercontent.com/13311657/121161295-c1d19000-c844-11eb-9cc0-d1f1be407739.png">

**Comment by davexparker** [comment]
Hi Colin. Support for this was added in v4.7. Get a binary from our downloads page (http://www.prismmodelchecker.org/download.php) or pull the latest code from GitHub and build.

**Comment by cap508** [comment]
Unfortunately I get the same issue with the 4.7 binary, I will try building from source.

<img width="771" alt="Screenshot 2021-06-08 at 10 43 13" src="https://user-images.githubusercontent.com/13311657/121163074-66080680-c846-11eb-9185-fd63763a954e.png">

**Comment by davexparker** [comment]
Oh yes, my mistake, sorry - the binary is not built for that architecture. But hopefully building from source will work with 4.7.

**Comment by cap508** [comment]
Thanks Dave, that works fine.
