### ISSUE TITLE
Typo in manual: 

### ISSUE THREAD

**Issue by fshahinfar1** [prismmodelchecker/prism#194]
Hello, 

Thank you for providing and maintaining PRISM manual. It is very helpful. While I was reading it, I found a typo.
In manual for  "The PRISM Language" section "Formulas & Labels" at line 135, the word "are" is repeated twice.

If you do not have the time to fix it I would be glad to send a PR.

https://github.com/prismmodelchecker/prism/blob/master/manual/ThePRISMLanguage/FormulasAndLabels.html#L135

Thanks

**Comment by davexparker** [comment]
Many thanks @fshahinfar1. This is now fixed online, and will get changed in the repo next time I do a release.
