### ISSUE TITLE
Build PRISM using Maven or Gradle and publish to MavenCentral

### ISSUE THREAD

**Issue by ifndefJOSH** [prismmodelchecker/prism#234]
As a project that's written in Java and C, I think PRISM might benefit from using a build system such as [Apache Maven](https://maven.apache.org/) or [Gradle](https://gradle.org/). Both of these have several benefits over PRISM's current system of using a GNU makefile, including:

+ Automatic management of dependencies. I'm not sure if all of PRISM's dependencies are on MavenCentral or a similar repository, but I would guess that at least most of them are.
+ You could quite easily create JAR files with less code than the makefile currently has (with Gradle/Groovy it's like 3 lines in `build.gradle`, not sure what it is in Maven)
+ Define the main class in the build file

And then you could publish the artifact from your build process to MavenCentral (or something similar) making it so other projects which use PRISM--e.g., STAMINA--can just declare PRISM as a dependency in their build files, and it will automatically get it for them.

All that said, I don't know if it would work super well with the C portion of PRISM.

**Comment by davexparker** [comment]
Thanks for this @ifndefJOSH. We have an open issue to discuss this issue: #223
