### ISSUE TITLE
Integrate prism-tests in the main repository?

### ISSUE THREAD

**Issue by kleinj** [prismmodelchecker/prism#24]
For discussion:

There have been suggestions that it would make sense to include the https://github.com/prismmodelchecker/prism-tests repository into the main PRISM repository.

Benefits:

- Easier to keep code and tests in sync.
- Allows pull requests against the PRISM repo to directly add test cases for fixes / new features.
- ...?

Cons:

- ...?

Location would be `prism-tests` at the top level?

**Comment by incaseoftrouble** [comment]
I guess I'm at least partly a reason for this discussion, so let me add some more points for it.

In general, tests should always be relative to a particular version. For example, when you develop a feature on some branch, you might want to have tests for this feature while you are developing without disrupting the testing of other devs (potentially working on different features).

The only downside I see are a few more bytes in the repo.

I strongly argue for setting up a CI pipeline, especially considering the amount of changes we are planning to implement. Speaking from experience, setting up CI with tests in a separate repo is a pain.

**Comment by davexparker** [comment]
Yes, I'm in favour of this too. There is already a partial mechanism for attaching test cases to branches, in that they can be put in a `tests` directory, which is found by the Makefile testing target (`tests`). But this proposed approach is cleaner and smooths the addition of new tests to the test suite after new branches are merged.

**Comment by davexparker** [comment]
I'm also up for a CI pipeline. We used to have a PRISM Jenkins server but that's no longer maintained unfortunately. I'd be happy to hear suggestions for ways forward on this. Although perhaps in a fresh issue I guess.
