### ISSUE TITLE
PTAParser.jj is outdated and does not match the rest of the codebase

### ISSUE THREAD

**Issue by muhrik** [prismmodelchecker/prism#32]
Hello @davexparker , @kleinj !
I would like to report a serious error in "PTAParser.jj" I found while working with @VojtechRehak and @Lkorenciak  on implementing some new features.

I (accidentally) recompiled all JavaCC files. This resulted in a build error.
After digging around, I realised that this commit
https://github.com/prismmodelchecker/prism/commit/4ad8e43e9f08f2c48b68537ef55a1b7c784a417b
has removed the default constructor for PTA, and replaced it with a parametric one.

```
-	public PTA()
+	public PTA(List<String> alphabet)
  	{
  		...
  	}

```
This would be okay, but the constructor calls were only changed in "PTAParser.java", not "PTAParser.jj".
From what I understand, "PTAParser.java" is autogenerated by JavaCC from "PTAParser.jj".
Thus, recompiling "PTAParser.jj" as of now generates an incompatible version of "PTAParser.java".

This can be easily fixed by doing the same modification as done for "PTAParser.java" in that commit to "PTAParser.jj" as well. That is, doing the following code change in "PTAParser.jj".

```
-                        pta = new PTA();
 +                        LinkedHashSet <String> alphabet = new LinkedHashSet<String>();
 +                        // Find alphabet
 +                        n = locationNames.size();
 +                        for (i = 0; i < n; i++) {
 +                            ArrayList<astTransition> tt = transitions.get(locationNames.get(i));
 +                            if (tt == null || tt.isEmpty()) continue;
 +                            for (astTransition t : tt) {
 +                            	if (t.action != null && !t.action.equals("")) {
 +                            		alphabet.add(t.action);
 +                            	}
 +                            }
 +                        }
 +                        // Create new PTA
 +                        pta = new PTA(new ArrayList<String> (alphabet));
```

Thanks!
Majo

**Comment by kleinj** [comment]
Good catch, fixed on master.

**Comment by VojtechRehak** [comment]
BTW. Is it worthy to have automatically generated files in the repository?
I would prefer to delete them all and keep only *.jj. Namely,
prism/src/parser/Prism3To4.jj
prism/src/parser/PrismParser.jj
prism/src/pta/parser/PTAParser.jj

**Comment by davexparker** [comment]
Most people will not have `javacc` installed and there also some issues with compatibility between different versions of it, so I think we need to keep them there.
