### ISSUE TITLE
GUI: Discoverability of possible user actions

### ISSUE THREAD

**Issue by kleinj** [prismmodelchecker/prism#41]
Having had a chance to look over the shoulders of several first time PRISM users, one small stumbling block in the beginning is the discoverability of possibly user interactions.

1. The tabs at the bottom, switching between model editor, properties editor, simulator and log take some time to find.
2. For the properties editor, adding the first property and adding a constant or label (via right click popup menu) seems to be difficult.
3. The `Simulate` option in the property pop-up is worded a bit confusingly; it could perhaps be made clearer that this refers to statistical model checking and not to simulating a path with the property taken into account.

Some ideas re 1:

- make the tabs larger, more noticable? Bold the `Log` tab, if there is new output?
- add `Switch to model view`, ... actions to the corresponding menus, as the first action? `Go to model`?
- move the tabs to the top?

Some ideas re 2:

- Visually, the constants and labels tables don't look editable (just gray background). Perhaps use the white background of the properties table? Add a grid?
- Allow double-click on the constant or lables table to add?
- Provide a tool-tip that suggests right-clicking?
- Have, as the last line of the table, a small `+` button for adding?
- Have, in the rule box with `Properties`, `Constants`, ... a small `+` button for adding? Not sure if that's technically possible, but would save screen space.

**Comment by davexparker** [comment]
Partially fixed in 447d4732bed04d10f2bcf28ea4a43c4f7da985f3 and c0c8e686b8aab6d8f7ec587eced498a99617d033.
