### ISSUE TITLE
org.w3c.dom not accessible when compiling from source

### ISSUE THREAD

**Issue by zgzn** [prismmodelchecker/prism#65]
I was compiling PRISM from source. I ran 'make' from the command line to build the C parts of PRISM first and then imported the project into Eclipse. After refreshing Eclipse, I got the error "The package org.w3c.dom is not accessible". I attached a screenshot.

I tried to download this missing package from Maven Central. I downloaded the two listed below and put them in lib subdirectory, but did not help to resolve the issue. 
dom-2.3.0-jaxb-1.0.6.jar
mathml-dom-java-2.0.jar

I am using Mac version 10.13.3 and Eclipse for RCP and RAP Developers, Version: Oxygen.2 Release (4.7.2). Any help is appreciated. 

<img width="1440" alt="screen shot 2018-03-09 at 12 43 34 am" src="https://user-images.githubusercontent.com/7920249/37197408-ebb16d88-2337-11e8-8ffd-23e18d9927e2.png">

**Comment by kleinj** [comment]
Hi,

this is strange. The `org.w3c.dom.*` packages are usually part of the Java JDK, so there is no need to install additional packages. What is your Java version?

I just checked, on my (older) version of Eclipse I get a working project (via the steps from http://www.prismmodelchecker.org/wiki/Developers/SettingUpEclipse). I'll try and reproduce with your version of Eclipse.

**Comment by kleinj** [comment]
Ok, in a clean Ubuntu VM (17.10), with Eclipse for RCP and RAP Developers (Oxygen.2) and OpenJDK 8 and a fresh clone of the git repository I can get to a working project using the normal steps.

So, I'm not sure what goes wrong for you. Could you try again with a new project? Perhaps something in the settings / paths got broken?

**Comment by zgzn** [comment]
Thanks for your fast response. I was using JRE Java SE 9.0.4 in Eclipse, and the complier compliance level was set to 9. After switching JRE to Java SE 8 [1.8.0_91] and the complier compliance level to 1.8, 
the errors were gone. Even with compliance level at 1.8, and Java SE 9.0.4, the errors did not show. It looks like the complier compliance level 9 was causing the issue.

**Comment by kleinj** [comment]
Great, thanks, that looks like a good work-around.

With JDK 9 I can replicate the issue; it's gone when switching the compliance level in Properties -> Java compiler to 1.8.

So, it looks like the Java 9 module system might be to blame. Curiously, compiling on the command line setting `-source 1.9 -target 1.9` works fine. So, might be an Eclipse issue not importing the correct module for those packages by default?

Anyways, we are currently targeting Java 8, so I guess the work-around of setting that in Eclipse is reasonable.

**Comment by zgzn** [comment]
Thanks for the detailed info. I will use Java 8 for now.
