### ISSUE TITLE
Generate strategy from shell

### ISSUE THREAD

**Issue by Fanda36** [prismmodelchecker/prism#96]
Is it possible to generate strategy and export via CLI? Something like `prism game.prism props.csl -prop 1 -generatestrategy -exportstrategy stratey.txt`

![image](https://user-images.githubusercontent.com/3972954/47494291-9b0bea00-d851-11e8-9d06-1f334b3fe80b.png)

**Comment by davexparker** [comment]
Yes: https://www.prismmodelchecker.org/manual/RunningPRISM/Strategies
